// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Dist__ShopController from "./dist/shop_controller"
application.register("dist--shop", Dist__ShopController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InventoryController from "./inventory_controller"
application.register("inventory", InventoryController)

import QuizController from "./quiz_controller"
application.register("quiz", QuizController)

import ShopController from "./shop_controller"
application.register("shop", ShopController)
